import Navbar from "@/components/shared/Navbar";
import "./globals.css";

import { Cormorant } from "next/font/google";
const cormorant = Cormorant({
    subsets: ["latin"],
    display: "swap",
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={cormorant.className}>
                <Navbar />
                {children}
            </body>
        </html>
    );
}
